global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.10.0.2:9100']
        labels:
          server: 'DATA-NODE-01'
          role: 'Database Cluster (MongoDB + Redis)'
      - targets: ['agent_node_exporter:9100']
        labels:
          server: 'APP-NODE-02'
          role: 'Core API & Redpanda Message Broker'
      - targets: ['10.30.0.2:9100']
        labels:
          server: 'GATEWAY-NODE-03'
          role: 'Egress Gateway & SSRF Defense Node'

  - job_name: 'loki'
    static_configs:
      - targets: ['mon_loki:3100']
