$ErrorActionPreference = "Stop"

$toolsPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$profilePath = $PROFILE

Write-Host "=================================================================" -ForegroundColor Cyan
Write-Host "Updating PowerShell Profile & Smart Tab-Completion..." -ForegroundColor Green
Write-Host "Tools Path:   $toolsPath" -ForegroundColor White
Write-Host "Profile Path: $profilePath" -ForegroundColor White
Write-Host "=================================================================" -ForegroundColor Cyan

$lines = @(
    "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8",
    "`$OutputEncoding = [System.Text.Encoding]::UTF8",
    "",
    "`$toolsPath = `"$toolsPath`"",
    "",
    "if (`$env:Path -notlike `"*`$toolsPath*`") {",
    "    `$env:Path = `"`$toolsPath;`$env:Path`"",
    "}",
    "",
    "function sowfkun {",
    "    . `"`$toolsPath\sowfkun.ps1`" @args",
    "}",
    "",
    "Register-ArgumentCompleter -Native -CommandName sowfkun, sowfkun.cmd, sowfkun.ps1, sowfkun.exe -ScriptBlock {",
    "    param(`$wordToComplete, `$commandAst, `$cursorPosition)",
    "    ",
    "    `$text = `$commandAst.ToString()",
    "    `$parts = `$text.TrimStart().Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)",
    "    `$isNewArg = `$text.EndsWith(' ') -or [string]::IsNullOrEmpty(`$wordToComplete)",
    "    `$argIndex = if (`$isNewArg) { `$parts.Count } else { [Math]::Max(0, `$parts.Count - 1) }",
    "",
    "    if (`$argIndex -le 1) {",
    "        `$topCommands = @('logs', 'infra-logs', 'verse-start', 'start', 'omicx-start', 'omicx', 'devtools', 'infra', 'deploy', 'deploy-gateway', 'sync-infra', 'verse-deploy', 'verse-deploy-gateway', 'download', 'sync-audio', 'help')",
    "        `$topCommands | Where-Object { `$_ -like `"`$wordToComplete*`" } | ForEach-Object {",
    "            [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)",
    "        }",
    "        return",
    "    }",
    "",
    "    `$subCmd = `$parts[1].ToLower()",
    "",
    "    if (`$subCmd -in @('logs', 'infra-logs', 'infra-log', 'log')) {",
    "        `$jsonPath = Join-Path (Split-Path -Parent `$toolsPath) '.servers\servers.json'",
    "        `$profiles = @('tailscale-dev', 'hybrid-dev')",
    "        `$allNodes = @('mongo', 'cache_mq', 'app', 'gateway')",
    "        `$allContainers = @('redis', 'kafka', 'redpanda', 'console', 'mongo', 'api', 'gateway', 'opensearch', 'dashboards', 'monitoring', 'promtail', 'all')",
    "        if (Test-Path `$jsonPath) {",
    "            try {",
    "                `$json = Get-Content `$jsonPath -Raw | ConvertFrom-Json",
    "                if (`$json.profiles) {",
    "                    `$profiles = @(`$json.profiles.PSObject.Properties.Name)",
    "                }",
    "            } catch {}",
    "        }",
    "        if (`$argIndex -eq 2) {",
    "            `$options = `$profiles + `$allNodes + `$allContainers + @('-f', '--follow', '--tail', '-t')",
    "            `$options | Where-Object { `$_ -like `"`$wordToComplete*`" } | ForEach-Object {",
    "                [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)",
    "            }",
    "            return",
    "        }",
    "        if (`$argIndex -eq 3) {",
    "            `$options = `$allNodes + `$allContainers + @('-f', '--follow', '--tail', '-t')",
    "            `$options | Where-Object { `$_ -like `"`$wordToComplete*`" } | ForEach-Object {",
    "                [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)",
    "            }",
    "            return",
    "        }",
    "        if (`$argIndex -ge 4) {",
    "            `$options = `$allContainers + @('-f', '--follow', '--tail', '-t')",
    "            `$options | Where-Object { `$_ -like `"`$wordToComplete*`" } | ForEach-Object {",
    "                [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)",
    "            }",
    "            return",
    "        }",
    "    }",
    "",
    "    if (`$subCmd -in @('devtools', 'dev-tools', 'devbox', 'dev-box', 'dev')) {",
    "        if (`$argIndex -eq 2) {",
    "            `$devActions = @('web', 'desktop', 'install', 'uninstall')",
    "            `$devActions | Where-Object { `$_ -like `"`$wordToComplete*`" } | ForEach-Object {",
    "                [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)",
    "            }",
    "            return",
    "        }",
    "    }",
    "",
    "    if (`$subCmd -in @('infra', 'infra-tunnel', 'tunnel')) {",
    "        if (`$argIndex -eq 2) {",
    "            `$infraActions = @('open', 'close', 'switch', 'status', 'logs')",
    "            `$infraActions | Where-Object { `$_ -like `"`$wordToComplete*`" } | ForEach-Object {",
    "                [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)",
    "            }",
    "            return",
    "        }",
    "        if (`$argIndex -ge 3) {",
    "            `$profiles = @('tailscale-dev', 'hybrid-dev', 'gcp-direct-dev', 'netcup-mongo-dev', 'all', 'mongo', 'cache', 'redis', 'kafka', 'app', 'gateway')",
    "            `$jsonPath = Join-Path (Split-Path -Parent `$toolsPath) '.servers\servers.json'",
    "            if (Test-Path `$jsonPath) {",
    "                try {",
    "                    `$json = Get-Content `$jsonPath -Raw | ConvertFrom-Json",
    "                    if (`$json.profiles) {",
    "                        `$profiles = @(`$json.profiles.PSObject.Properties.Name) + @('all', 'mongo', 'cache', 'redis', 'kafka', 'app', 'gateway')",
    "                    }",
    "                } catch {}",
    "            }",
    "            `$profiles | Where-Object { `$_ -like `"`$wordToComplete*`" } | ForEach-Object {",
    "                [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)",
    "            }",
    "            return",
    "        }",
    "    }",
    "",
    "    if (`$subCmd -in @('verse-deploy', 'verse-deploy-gateway', 'verse-deploy-gw', 'deploy', 'deploy-api', 'deploy-gw', 'sync-infra', 'sync-infrastructure', 'infra-sync')) {",
    "        if (`$argIndex -eq 2) {",
    "            `$profiles = @('tailscale-dev', 'hybrid-dev', 'gcp-direct-dev', 'tailscale-prod')",
    "            `$jsonPath = Join-Path (Split-Path -Parent `$toolsPath) '.servers\servers.json'",
    "            if (Test-Path `$jsonPath) {",
    "                try {",
    "                    `$json = Get-Content `$jsonPath -Raw | ConvertFrom-Json",
    "                    if (`$json.profiles) {",
    "                        `$profiles = @(`$json.profiles.PSObject.Properties.Name)",
    "                    }",
    "                } catch {}",
    "            }",
    "            `$profiles | Where-Object { `$_ -like `"`$wordToComplete*`" } | ForEach-Object {",
    "                [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)",
    "            }",
    "            return",
    "        }",
    "        if (`$argIndex -ge 3) {",
    "            `$envs = @('dev', 'staging', 'prod')",
    "            `$envs | Where-Object { `$_ -like `"`$wordToComplete*`" } | ForEach-Object {",
    "                [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_)",
    "            }",
    "            return",
    "        }",
    "    }",
    "}"
)

$profileDir = Split-Path -Parent $profilePath
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

$lines | Out-File -FilePath $profilePath -Encoding UTF8 -Force

Write-Host "INSTALLATION SUCCESSFUL!" -ForegroundColor Green
Write-Host "Tab-Completion is now fully active for sowfkun, infra, verse-deploy!" -ForegroundColor White
Write-Host "=================================================================" -ForegroundColor Cyan
